# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

input {
	kb_layout = de,us
	kb_options = caps:escape

	touchpad {
    		disable_while_typing = false
		natural_scroll = true
		scroll_factor = 0.15
		tap-and-drag = true
	}
}

# Main monitor gets workspaces 1-5
workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1

# Second monitor gets workspaces 6-10
workspace = 6, monitor:DP-3, default:true
workspace = 7, monitor:DP-3
workspace = 8, monitor:DP-3
workspace = 9, monitor:DP-3
workspace = 10,monitor:DP-3

xwayland {
	force_zero_scaling = true
	use_nearest_neighbor = true
}

env = GDK_SCALE,1.25
env = XCURSOR_SIZE,32

general {
	gaps_in = 3

	col.active_border = rgba(ffffff33)
	col.inactive_border = rgba(ffffff1a)
	border_size = 1
}
 
decoration {
	blur {
		enabled = true
		size = 8
		passes = 2
		#new_optimizations = true
		#ignore_opacity = true
		#xray = false
	}
}

windowrule {
    name = global-opacity
    opacity = 0.89 override 0.89 override
    match:class = ^(.*)$
}
 
windowrule {
    name = figma-opacity
    opacity = 1.0 1.0
    match:title = ^(.*Figma.*)$
}
