# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

input {
	kb_layout = de,us
	kb_options = caps:escape
}

xwayland {
	force_zero_scaling = true
	use_nearest_neighbor = true
}

env = GDK_SCALE,1.25
env = XCURSOR_SIZE,32

# Uncomment to apply global transparency to all windows:
windowrulev2 = opacity 0.89 override 0.89 override, class:.*
windowrulev2 = opacity 1.0 1.0,title:^(.*Figma.*)$
#windowrulev2 = opacity 1 override 1 override, class:.*
