# See https://wiki.hyprland.org/Configuring/Binds/

##! Utilities

# Recording stuff
bindd = Super+Alt, R, Record region (no sound), exec, ~/.config/scripts/record.sh # Record region (no sound)
bindd = Ctrl+Alt, R, Record screen (no sound), exec, ~/.config/scripts/record.sh --fullscreen # [hidden] Record screen (no sound)
bindd = Super+Shift+Alt, R, Record screen (with sound), exec, ~/.config/scripts/record.sh --fullscreen-sound# Record screen (with sound)


##! Window

# Focusing
#/# bind = Super, ←/↑/→/↓,, # Focus in direction
bind = Super, Left, movefocus, l # [hidden]
bind = Super, Right, movefocus, r # [hidden]
bind = Super, Up, movefocus, u # [hidden]
bind = Super, Down, movefocus, d # [hidden]
#/# bind = Super+Shift, ←/↑/→/↓,, # Move in direction
bind = Super+Shift, Left, movewindow, l # [hidden]
bind = Super+Shift, Right, movewindow, r # [hidden]
bind = Super+Shift, Up, movewindow, u # [hidden]
bind = Super+Shift, Down, movewindow, d # [hidden]
bind = Alt, F4, killactive, # [hidden] Close (Windows)
bind = Super, Delete, killactive, # Close
bind = Super, Escape, killactive, # Close
bind = Super, Q, killactive, # Close
bind = Super+Shift+Alt, Q, exec, hyprctl kill # Forcefully zap a window

# Window split ratio
#/# binde = Super+Alt, ←/→,, # Adjust split ratio
binde = Super+Alt, Left, splitratio, -0.1 # [hidden]
binde = Super+Alt, Right, splitratio, +0.1 # [hidden]
binde = Super, M, togglesplit

#/# bind = Super+Alt, Hash,, # Send to workspace # (1, 2, 3,...)
#bind = Super+Shift, 1, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 1 # [hidden]
#bind = Super+Shift, 2, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 2 # [hidden]
#bind = Super+Shift, 3, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 3 # [hidden]
#bind = Super+Shift, 4, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 4 # [hidden]
#bind = Super+Shift, 5, exec, ~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 5 # [hidden]

#/# bind = Super+Shift, Page_↑/↓,, # Send to workspace left/right
bind = Ctrl+Super+Shift, Right, movetoworkspace, r+1 # [hidden]
bind = Ctrl+Super+Shift, Left, movetoworkspace, r-1 # [hidden]

##! Apps
bind = Super, Return, exec, ~/.config/scripts/launch_first_available.sh "${TERMINAL}" "kitty -1" "foot" "alacritty" "wezterm" "konsole" "kgx" "uxterm" "xterm" # Terminal
bind = Super, E, exec, ~/.config/scripts/launch_first_available.sh "dolphin" "nautilus" "nemo" "thunar" "${TERMINAL}" "kitty -1 fish -c yazi" # File manager
bind = Super, K, exec, gtk-launch WebApp-NotionCalendar5640
bind = Super, W, exec, ~/.config/scripts/launch_first_available.sh "vivaldi" "google-chrome-stable" "zen-browser" "firefox" "brave" "chromium" "microsoft-edge-stable" "opera" "librewolf" # Browser
bind = Super, C, exec, ~/.config/scripts/launch_first_available.sh "code" "codium" "cursor" "zed" "zedit" "zeditor" "kate" "gnome-text-editor" "emacs" "command -v nvim && kitty -1 nvim" "command -v micro && kitty -1 micro" # Code editor
bind = Super, I, exec, XDG_CURRENT_DESKTOP=gnome ~/.config/scripts/launch_first_available.sh "gnome-control-center" "qs -p ~/.config/quickshell/$qsConfig/settings.qml" "systemsettings" "better-control" # Settings app
