# Dank Linux DMS layer rules
# Based on: https://danklinux.com/docs/dankmaterialshell/layers#blur-settings

# Blur for modals (clipboard, settings, spotlight, etc.)
$blur_modal = dms:(polkit|notification-center-modal|workspace-overview|color-picker|clipboard|spotlight|settings|process-list-modal|power-menu|file-browser|bluetooth-pairing|hyprkeybinds|network-info|network-info-wired|wifi-password|confirm-modal|modal)
layerrule = noanim, $blur_modal

# Blur for popouts and bar components
$blur_shell = dms:(bar|tooltip|toast|dock-context-menu|tray-menu-window|control-center|notification-center-popout|dash|system-update|process-list-popout|battery|popout|app-launcher|dock|slideout)
layerrule = noanim, $blur_shell
#layerrule = ignorezero, $blur_shell

# Blur for notifications and OSD
layerrule = noanim, dms:notification-popup
layerrule = noanim, dms:osd
